#if defined _inc_codbuf_code
	#undef _inc_codbuf_code
#endif

#include "codbuf_code_100"
#include "codbuf_code_100"
#include "codbuf_code_100"
#include "codbuf_code_100"
#include "codbuf_code_100"
#include "codbuf_code_100"
#include "codbuf_code_100"
#include "codbuf_code_100"
#include "codbuf_code_100"
#include "codbuf_code_100"
#include "codbuf_code_10"
#include "codbuf_code_10"
#emit NOP
#emit NOP
#emit NOP
#emit NOP
